name: flutter_webapi_second_course
description: Aplicação para o segundo curso de WebAPI da Formação Flutter da Alura

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  google_fonts: ^3.0.1
  http: ^0.13.4
  http_interceptor: ^1.0.2
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true